version: '3.8'

services:
  handwriting:
    build: .
    working_dir: /app/src
    volumes:
      # Mount the source code for development
      - ./src:/app/src
      # Mount the data directory
      - ./data:/data
      # Mount the output directory to persist all generated files
      - ./output/prep:/app/output/prep
    command: /bin/bash
